FROM ubuntu:18.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q && apt-get install -qy \
      man make git netcat

WORKDIR /workdir
VOLUME  /workdir
EXPOSE «value EXPOSE from bin/vars»

# vim: ft=Dockerfile
